// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLMCAzYBLoGFeDZo3uxh4NChFG1-SbcY',
    appId: '1:500856361789:web:3e21ee9b0717d4897aab54',
    messagingSenderId: '500856361789',
    projectId: 'pinterest-clone-8d38e',
    authDomain: 'pinterest-clone-8d38e.firebaseapp.com',
    storageBucket: 'pinterest-clone-8d38e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPonXTCGB1GqTjQvw-qPkTTg5HSV4qoHg',
    appId: '1:500856361789:android:85285bdac17db6717aab54',
    messagingSenderId: '500856361789',
    projectId: 'pinterest-clone-8d38e',
    storageBucket: 'pinterest-clone-8d38e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzQFcZUYNQlpvjqMW-oRSAOa4EXKcofOo',
    appId: '1:500856361789:ios:0dc52697c48078987aab54',
    messagingSenderId: '500856361789',
    projectId: 'pinterest-clone-8d38e',
    storageBucket: 'pinterest-clone-8d38e.appspot.com',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzQFcZUYNQlpvjqMW-oRSAOa4EXKcofOo',
    appId: '1:500856361789:ios:0dc52697c48078987aab54',
    messagingSenderId: '500856361789',
    projectId: 'pinterest-clone-8d38e',
    storageBucket: 'pinterest-clone-8d38e.appspot.com',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLMCAzYBLoGFeDZo3uxh4NChFG1-SbcY',
    appId: '1:500856361789:web:68ba8820ab80703d7aab54',
    messagingSenderId: '500856361789',
    projectId: 'pinterest-clone-8d38e',
    authDomain: 'pinterest-clone-8d38e.firebaseapp.com',
    storageBucket: 'pinterest-clone-8d38e.appspot.com',
  );
}
